/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package atm.gui;

import atm.controller.AccountController;
import atm.db.DBConnection;
import atm.model.Account;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author viniciusbeletella
 */
public class LoginPage extends javax.swing.JPanel {

    /** Creates new form LoginPage */
    public LoginPage() {
        initComponents();
        
        DBConnection conn = new DBConnection();
        
        conn.connection();
        

        
        accessAccountButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
              
                AccountController  accountController = new AccountController();
              
                Account account = accountController.login(accountNumberText.getText(), String.valueOf(pinPassword.getPassword()));
                
                // Database error handling on AccountController and DB Connection.
                if( account.getId() == 0){
                    JOptionPane.showMessageDialog(null, "Account and pin details does not match ");
                }else{
                    
                JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(accessAccountButton);
                
                topFrame.setContentPane (new MainMenuPage(account));
                topFrame.invalidate();
                topFrame.validate();
               
                
                }
                
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accountNumberLabel = new javax.swing.JLabel();
        pinLabel = new javax.swing.JLabel();
        accountNumberText = new javax.swing.JTextField();
        welcomeLabel = new javax.swing.JLabel();
        accessAccountButton = new javax.swing.JButton();
        pinPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        accountNumberLabel.setText("Account Number:");

        pinLabel.setText("Pin:");

        accountNumberText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountNumberTextActionPerformed(evt);
            }
        });

        welcomeLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        welcomeLabel.setText("Welcome!");

        accessAccountButton.setText("Access Account");

        pinPassword.setEchoChar('\u25cf');
        pinPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinPasswordActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/Img/download.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(accessAccountButton))
                            .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(accountNumberLabel)
                                    .addComponent(pinLabel))
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(accountNumberText, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                    .addComponent(pinPassword))))
                        .addContainerGap(93, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountNumberLabel)
                    .addComponent(accountNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pinLabel)
                    .addComponent(pinPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(accessAccountButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pinPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pinPasswordActionPerformed

    private void accountNumberTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountNumberTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountNumberTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accessAccountButton;
    private javax.swing.JLabel accountNumberLabel;
    private javax.swing.JTextField accountNumberText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel pinLabel;
    private javax.swing.JPasswordField pinPassword;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables

}
