/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atm.gui;

import atm.model.Account;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author viniciusbeletella
 */
public class MainMenuPage extends javax.swing.JPanel {
    

    /**
     * Creates new form MainMenuPage
     */
    public MainMenuPage(Account account) {
        initComponents();
        
        
        choiceButton.addActionListener(new ActionListener() {
            
            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println(choiceText.getText());
                
                
                 JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(choiceButton);
                 
                 switch (choiceText.getText()){
                     case "1":
                         topFrame.setContentPane(new BalancePage (account));
                         break;
                     case "2":
                         topFrame.setContentPane(new WithdrawMenuPage(account));
                         break;
                     case "3":
                         topFrame.setContentPane(new DepositPage(account));
                         break;
                     case "4":
                         topFrame.setContentPane(new LoginPage());
                         break;
                     default:
                         JOptionPane.showMessageDialog(null, "Please select an option between 1 and 4");
                        
                         
                 }
            topFrame.invalidate();
            topFrame.validate();
                
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        menuList = new javax.swing.JList<>();
        menuHeaderLabel = new javax.swing.JLabel();
        enterChoiceLabel = new javax.swing.JLabel();
        choiceText = new javax.swing.JTextField();
        choiceButton = new javax.swing.JButton();

        menuList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1 - View my balance", "2 - Withdraw cash", "3 - Deposit funds", "4 - Exit" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(menuList);

        menuHeaderLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        menuHeaderLabel.setText("Main Menu: ");

        enterChoiceLabel.setText("Enter a choice: ");

        choiceButton.setText("GO!");
        choiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choiceButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuHeaderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(choiceButton)
                                .addComponent(enterChoiceLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(choiceText, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuHeaderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterChoiceLabel)
                    .addComponent(choiceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(choiceButton)
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void choiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choiceButtonActionPerformed
        // TODO add your handling code here:
        System.out.println(choiceText.getText());
    }//GEN-LAST:event_choiceButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton choiceButton;
    private javax.swing.JTextField choiceText;
    private javax.swing.JLabel enterChoiceLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel menuHeaderLabel;
    private javax.swing.JList<String> menuList;
    // End of variables declaration//GEN-END:variables
}
