/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atm.gui;


import atm.controller.AccountController;
import atm.model.Account;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;


/**
 *
 * @author viniciusbeletella
 */
public class WithdrawMenuPage extends javax.swing.JPanel {
    
    
    /**
     * Creates new form WithdrawMenuPage
     */
    public WithdrawMenuPage(Account account) {
        initComponents();
        
        
        choiceButton.addActionListener(new ActionListener() {
            
            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println(choiceButton.getText());
                
                AccountController wt = new AccountController();
                        
                
                 JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(choiceButton);
                 
                 switch (choiceText.getText()){
                     case "1":
                         //topFrame.setContentPane(new WithdrawTest(account, -20));
                            account.setBalance(account.getBalance() - 20.00);
                         break;
                     case "2":
                         //topFrame.setContentPane(new WithdrawTest(account, -40));
                        account.setBalance(account.getBalance() - 40.00);
                         break;
                     case "3":
                         account.setBalance(account.getBalance() - 60.00);
                         //topFrame.setContentPane(new WithdrawTest(account, -60));    
                         break;
                     case "4":
                           account.setBalance(account.getBalance() - 100.00);
                         //topFrame.setContentPane(new WithdrawTest(account, -100));  
                         break;
                     case "5":
                          account.setBalance(account.getBalance() - 200.00);
                         //topFrame.setContentPane(new DepositOut(account, 5200));  
                         break;
                     case "6":
                         JOptionPane.showMessageDialog(null, "Transaction was canceled"); 
                         topFrame.setContentPane(new LoginPage());
                         break;
                     default:
                         JOptionPane.showMessageDialog(null, "Please select an option between 1 and 6");
                        
                         
                 }
                 
                 wt.updateBalance(account); 
                 
                 topFrame.setContentPane(new BalancePage(account));

                topFrame.invalidate();
                topFrame.validate();
                
            }
        });
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        withdrawMenuheader = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        withdrawMenuList = new javax.swing.JList<>();
        withdrawchoiceLabel = new javax.swing.JLabel();
        choiceButton = new javax.swing.JButton();
        choiceText = new javax.swing.JTextField();

        withdrawMenuheader.setText("Withdrawal options:");

        withdrawMenuList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1- $ 20", "2 - $40", "3 - $60", "4 - $100", "5 - $200", "6 - Cancel transaction" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(withdrawMenuList);

        withdrawchoiceLabel.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        withdrawchoiceLabel.setText("Choose a wihdrawal option (1-6):");

        choiceButton.setText("Go!");
        choiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choiceButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(choiceButton)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(withdrawchoiceLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(choiceText, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(withdrawMenuheader)))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(withdrawMenuheader)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(withdrawchoiceLabel)
                    .addComponent(choiceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(choiceButton)
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void choiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choiceButtonActionPerformed

        // TODO add your handling code here:
        System.out.println(choiceText.getText());
    }//GEN-LAST:event_choiceButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton choiceButton;
    private javax.swing.JTextField choiceText;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> withdrawMenuList;
    private javax.swing.JLabel withdrawMenuheader;
    private javax.swing.JLabel withdrawchoiceLabel;
    // End of variables declaration//GEN-END:variables
}
